### ISSUE TITLE
Enable aarch64

### ISSUE THREAD

**Issue by RossComputerGuy** [flathub/com.inochi2d.inochi-session#3]
I see it was disabled in https://github.com/flathub/com.inochi2d.inochi-session/commit/e6e5ac8f456c8fa2463028892b60f1c9270e400d 4 months ago, why was it disabled? Is it expected to be enabled in the future? I plan on doing VTubing stuff on aarch64 and it would be great to use Inochi from Flathub.

**Comment by grillo-delmal** [comment]
The project maintainer requested to remove the aarch64 build cos of the maintenance burden it implies to her to support it.
If you don't mind dealing with the problems that might arise by running on that environment, you can build it yourself ^^
